work_site/inw/urls.py
from django.urls import path
from .views import TableData, UploadData, InwModelCreateView, InwModelUpdateView, ConfirmDeleteList, \
    download_data_as_excel

app_name = 'myapp'

urlpatterns = [
    path('table/', TableData.as_view(), name='table'),
    path('upload/', UploadData.as_view(), name='upload'),
    path('create/', InwModelCreateView.as_view(), name='create'),
    path('update/<int:pk>', InwModelUpdateView.as_view(), name='update'),
    path('delete/', ConfirmDeleteList.as_view(), name='list'),
    path('download/', download_data_as_excel, name='download'),
    path('download/<int:pk>', download_data_as_excel, name='download'),

]

handler404 = "work_site.views.page_not_found_view"

work_site/work_site/urls.py
from django.contrib import admin
from django.urls import path,include,reverse_lazy
from .views import HomeView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inw/', include('inw.urls')),
    path('accounts/', include('accounts.urls')),
    path('', HomeView.as_view(), name='home'),
]

work_site/inw/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class UploadModel(models.Model):
    name = models.CharField(max_length=50, null=False)
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} {self.date} {self.user}'


class InwModel(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    EAN = models.IntegerField(blank=True, null=True)
    quantity = models.IntegerField(default='1')
    upload = models.ForeignKey(UploadModel, on_delete=models.CASCADE, related_name='set')

    def __str__(self):
        return f'{self.name} {self.EAN} {self.quantity}'

work_site/inw/forms.py
from django import forms
from .models import InwModel, UploadModel



class SurplusLackInputForm(forms.Form):
    lack_check = forms.BooleanField(required=False, initial=True, widget=forms.CheckboxInput(attrs={
        'class': "form-check-input",
        'id': "radio-lack",
        'role': "switch",
    }),
                                    label="Braki",
                                    label_suffix=''
                                    )

    surplus_check = forms.BooleanField(required=False, initial=True, widget=forms.CheckboxInput(attrs={
        'class': "form-check-input",
        'id': "radio-lack",
        'role': "switch",
    }),
                                       label="Nadwyżki",
                                       label_suffix=''
                                       )


class EditForm(forms.ModelForm):
    class Meta:
        model = InwModel
        fields = ["quantity"]
        widgets = {
            'quantity': forms.NumberInput()
        }
        labels = {
            'quantity': 'Ilość',
        }


class CreateDataForm(forms.ModelForm):
    class Meta:
        model = InwModel
        fields = ["name", "EAN", "quantity", "upload"]
        widgets = {
            'name': forms.TextInput(attrs={'class': "form-control", 'placeholder': "Etui"}),
            'EAN': forms.NumberInput(attrs={'class': "form-control", 'placeholder': "123456789"}),
            'quantity': forms.NumberInput(attrs={'class': "form-control"}),
            'upload': forms.Select(attrs={"class": "form-select", }),
        }
        labels = {
            'name': 'Nazwa',
            'quantity': 'Ilość',
            'upload': 'Zbiór',
        }
        help_texts = {
            'upload': 'Wymagane jest wybranie któregoś z zbiorów',
        }


class UploadModelFormSelect(forms.ModelForm):
    class Meta:
        model = InwModel
        fields = ['upload']
        widgets = {
            'upload': forms.Select(attrs={
                "class": "form-select",
                'aria-label': "Default select example"})
        }
        labels = {
            'upload': ''
        }

    def __init__(self, user=None, **kwargs):
        super(UploadModelFormSelect, self).__init__(**kwargs)
        if user:
            self.fields['upload'].queryset = UploadModel.objects.filter(user=user)

work_site/inw/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
import pandas as pd
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font, Alignment
from datetime import datetime
from .models import InwModel, UploadModel
from .forms import CreateDataForm, SurplusLackInputForm, UploadModelFormSelect, EditForm
from django.views.generic import View, UpdateView, CreateView
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


# REDIRECT PREVIOUS PAGE METHOD FOR GENERIC CLASS VIEW

class RedirectToPreviousMixin:
    default_redirect = '/'

    def get(self, request, *args, **kwargs):
        request.session['previous_page'] = request.META.get('HTTP_REFERER', self.default_redirect)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return self.request.session['previous_page']


@login_required(login_url="/login")
def download_data_as_excel(request, pk):
    if request.method == 'GET':
        model_queryset = InwModel.objects.filter(upload=pk)
        upload_date = UploadModel.objects.get(id=pk)
        response = HttpResponse(
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        )
        response['Content-Disposition'] = f"attachment; filename={upload_date}-akcesoria.xlsx"
        workbook = Workbook()
        worksheet = workbook.active
        worksheet.title = 'Akcesoria'
        columns = [
            'ID',
            'Nazwa',
            'EAN',
            'Ilość',
        ]
        row_num = 1
        for col_num, column_title in enumerate(columns, 1):
            cell = worksheet.cell(row=row_num, column=col_num)
            wsc = worksheet[cell.coordinate]
            cell.value = column_title
            column_letter = get_column_letter(col_num)
            column_dimensions = worksheet.column_dimensions[column_letter]
            wsc.font = Font(bold=True, size="13")
            wsc.alignment = Alignment(horizontal='center', vertical='center')
            worksheet.row_dimensions[1].height = 35
            if column_title == 'ID' or column_title == 'Ilość':
                column_dimensions.width = 8
            elif column_title == 'EAN':
                column_dimensions.width = 30
            else:
                column_dimensions.width = 40
        for model in model_queryset:
            row_num += 1
            row = [
                row_num - 1,
                model.name,
                str(model.EAN),
                model.quantity,
            ]
            for col_num, cell_value in enumerate(row, 1):
                cell = worksheet.cell(row=row_num, column=col_num)
                wsc = worksheet[cell.coordinate]
                if cell.column_letter == 'A':
                    wsc.alignment = Alignment(horizontal='left')
                elif cell.column_letter == 'C':
                    wsc.alignment = Alignment(horizontal='center')
                elif cell.column_letter == 'D':
                    if cell_value > 0:
                        wsc.font = Font(color="0000FF00")
                    elif cell_value < 0:
                        wsc.font = Font(color="00FF0000")
                cell.value = cell_value
        worksheet.auto_filter.ref = worksheet.dimensions
        workbook.save(response)
        return response


class ConfirmDeleteList(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request, *args, **kwargs):
        request.session['previous_page'] = request.META.get('HTTP_REFERER', '/')
        id_list = request.GET.getlist('delete')
        product = InwModel
        if len(id_list) == 0:
            messages.add_message(request, messages.ERROR, 'Musisz wybrać pozycję żeby usunąć!')
            return redirect(request.session['previous_page'])
        else:
            objects = product.objects.filter(id__in=id_list)
            return render(request, 'inw/inwmodel_delete_list.html', {'objects': objects})

    def post(self, request, *args, **kwargs):
        id_list = request.GET.getlist('delete')
        product = InwModel
        container = UploadModel
        product_id = product.objects.get(pk=id_list[0])
        field_name_val = getattr(product_id, 'upload')
        product.objects.filter(id__in=id_list).delete()
        field_len = len(field_name_val.set.all())
        if field_len == 0:
            container.objects.get(id=field_name_val.id).delete()
            messages.add_message(request, messages.SUCCESS, f'Usunięto wszystkie obiekty w {field_name_val}!')
            return redirect(reverse('myapp:table'))
        messages.add_message(request, messages.SUCCESS, f'Usunięto {len(id_list)} elementów!')
        return redirect(request.session['previous_page'])


class UploadData(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        return render(request, 'inw/upload_form_page.html')

    def post(self, request, *args, **kwargs):
        from .upload_scripts.upload_scripts import excel_inf_to_list, excel_sap_to_dict, process_excel_files, \
            handle_uploaded
        from .upload_scripts.user_query_check_NaN import check_NaN
        try:
            sap, inw = handle_uploaded(request.FILES)
            user = request.user
            df_sap = pd.read_excel(sap)
            df_inw = pd.read_excel(inw, header=None)
            inw_list = excel_inf_to_list(df_inw, df_sap)
            sap_dict = excel_sap_to_dict(df_sap)
            new_data = process_excel_files(inw_list, sap_dict)
            new_data_check_null = new_data['Zapas ogółem']
            if all(x == new_data_check_null[0] for x in new_data_check_null):
                link = reverse('myapp:table')
                response = {'url': link}
                messages.add_message(request, messages.SUCCESS, 'Nie znaleziono żadnych nieprawidłowośći!')
                return JsonResponse(response)
            user_query = UploadModel.objects.filter(user=user)
            name = check_NaN(user_query, new_data)
            upload_file = UploadModel(name=name, user=user)
            upload_file.save()
            sql_data = {
                'name': '',
                'EAN': '',
                'quantity': '',
                'upload': upload_file
            }
            index = -1
            for value in new_data['Zapas ogółem']:
                index += 1
                if value != 0:
                    sql_data['quantity'] = new_data['Zapas ogółem'][index]
                    sql_data['EAN'] = new_data['EAN'][index]
                    sql_data['name'] = new_data['Krótki tekst materiału'][index]
                    model = InwModel(**sql_data)
                    model.save()
            id = getattr(upload_file, 'id')
            link = reverse('myapp:table')
            response = {'url': link}
            messages.add_message(request, messages.SUCCESS, 'Plik został przesłany!')
        except KeyError:
            messages.add_message(request, messages.ERROR, 'Musisz przesłać dwa pliki SAP i INW! Kod błędu 1, SPRWADŹ FAQ')
            link = reverse('myapp:upload')
            response = {'url': link}
        except ValueError:
            messages.add_message(request, messages.ERROR, 'Sprawdź poprawność plików! Kod błędu 2, SPRAWDŹ FAQ')
            link = reverse('myapp:upload')
            response = {'url': link}
        return JsonResponse(response)


class TableData(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request, **kwargs):
        checkboxesform = SurplusLackInputForm()
        selectform = UploadModelFormSelect(user=request.user)
        ProductModel = InwModel
        productContainerModel = UploadModel
        context = {
            'checkboxesform': checkboxesform,
            'selectform': selectform,
        }
        intaial_data = {

        }
        try:
            if checkboxesform.is_valid and selectform.is_valid:
                productcontainer = productContainerModel.objects.get(id=request.GET['upload'])
                products = ProductModel.objects.filter(upload=productcontainer)
                intaial_data['upload'] = productcontainer
                context['selectform'] = UploadModelFormSelect(initial=intaial_data, user=request.user)
                if 'surplus_check' in request.GET and 'lack_check' not in request.GET:
                    checkboxesform.fields['lack_check'].initial = False
                    products = products.filter(quantity__gt=0)
                    context["products"] = products
                elif 'lack_check' in request.GET and 'surplus_check' not in request.GET:
                    checkboxesform.fields['surplus_check'].initial = False
                    products = products.filter(quantity__lt=0)
                    context["products"] = products
                else:
                    context["products"] = products
        finally:
            return render(request, 'inw/table_form.html', context=context)


class InwModelCreateView(RedirectToPreviousMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = CreateDataForm
    model = InwModel
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('myapp:table')
    success_message = "Obiekt %(name)s został utworzony!"
    login_url = '/login/'

    def get_form(self, *args, **kwargs):
        form = super(InwModelCreateView, self).get_form(*args, **kwargs)
        form.fields['upload'].queryset = UploadModel.objects.filter(user=self.request.user)
        return form


class InwModelUpdateView(RedirectToPreviousMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = EditForm
    model = InwModel

work_site/inw/templates/inw/inwmodel_create_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Create {% endblock %}

{% load crispy_forms_tags %}
{% block nav %}
<h1><img class="header-icon" src="{% static 'images/addHeader.png' %}">Dodaj</h1>
{% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div>
        {{form|crispy}}
        <div class="mb-0">
            <button type="submit" class="btn btn-primary col-12 m1">Zapisz</button>
            <a class="btn btn-danger col-12 m1" href="{% url 'myapp:table' %}">Wróć</a>
        </div>
    </div>
</form>
{% endblock %}

work_site/inw/templates/inw/inwmodel_delete_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Delete {% endblock %}





{% block content %}
<h1><img class="header-icon" src="{% static 'images/deleteHeader.png' %}">Czy chcesz usunąć ?</h1>

<form method="POST">
    {% csrf_token %}
    <ul class="list-group">
        {% for object in objects %}
            <li class="list-group-item d-flex justify-content-between align-items-center liElement {">
                <div class="margin-name">
                    <p class="deleteTitle">Produkt:</p> {{ object.name }}
                </div>
                <div class="margin-ean">
                    <p class="deleteTitle">EAN:</p>{{ object.EAN }}
                </div>
                <div>
                    <span class="badge badge-primary badge-pill">{{ object.quantity }}</span>
                </div>
            </li>
        {% endfor %}
    </ul>
    <div class="mb-0">
        <button type="submit" class="btn btn-primary col-12 m1" name="confirm">Confirm Delete</button>
        <a class="btn btn-danger col-12 m1" href="{% url 'myapp:table' %}">Wróć</a>
    </div>
</form>
{% endblock %}

work_site/inw/templates/inw/inwmodel_update_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit {% endblock %}

{% block nav %}
<h1><img class="header-icon" src="{% static 'images/editHeader.png' %}">Edytuj</h1>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <div class="mb-0">
        <button class="btn btn-primary col-12 m1" type="submit">Zapisz</button>
        <a class="btn btn-danger col-12 m1" href="{% url 'myapp:table' %}">Wróć</a>
    </div>
</form>
{% endblock %}

work_site/inw/templates/inw/messages.html
{% for message in messages %}
    <div class="alert {{ message.tags }}" role="alert">
        {{ message }}
    </div>
{% endfor %}

work_site/inw/templates/inw/table.html
{% extends 'base.html' %}

{% block title %}Table{% endblock %}

{% block content %}
    <table class="table table-hover">
        <thead class=>
            <tr>
                <th>Nazwa</th>
                <th>EAN</th>
                <th>Ilosc</th>
            </tr>
        </thead>
        {% for value in values %}
            <tr>
                <td>
                    {{ value.Nazwa }}
                    <ul class="nav">
                        <li class="nav-item"><a class="nav-link active" href="/inw/delete/{{value.id}}">Delete</a></li>
                    </ul>
                </td>
                <td>{{ value.EAN }}</td>
                <td>
                    <form method="post">
                        {% csrf_token %}
                        {{ value.Ilosc }}>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

work_site/inw/templates/inw/table_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Table {% endblock %}
{% block script %}
<!-- Custom JS -->
<script src="{% static 'js/checkbox.js' %}"></script>
<script src="{% static 'js/sort-table.js' %}"></script>
<script src="{% static 'js/clickrow.js' %}"></script>
{% endblock %}


{% block nav %}
<div class="form-control" id="flex">
    <h1 id="Th1"><img class="header-icon" src="{% static 'images/table_icon.png' %}">Tabela</h1>
    {% include 'inw/messages.html' %}
    <form method="GET">
        <div class="buttons">
            <button class="btn btn-info btn-10-em" type="submit" value="Check">Filtruj</button>
            {% if selectform.upload.value == None %}
            <button class="btn btn-danger btn-10-em" form="list" type="submit" value="delete" disabled>Usuń</button>
            <a class="btn btn-primary btn-10-em disabled" href="{% url 'myapp:download' %}{{selectform.upload.value}}">Pobierz
                Excel</a>
            {% else %}
            <button class="btn btn-danger btn-10-em" form="list" type="submit" value="delete">Usuń</button>
            <a class="btn btn-primary btn-10-em" href="/inw/download/{{selectform.upload.value}}">Pobierz Excel</a>
            {% endif %}
        </div>
        {% for checkform in checkboxesform %}
        <div class="form-check form-switch" id="inline">
            {{checkform}}{{checkform.label_tag}}
        </div>
        {% endfor %}
        {{ selectform }}
    </form>
    {% endblock %}
    {% block content %}
    <form action="{% url 'myapp:list' %}" class="inline" id="list" method="GET">
        <table class="table table-hover js-sort-table" id="sortable">
            <thead class="tableElementThead">
            <tr>
                {% if selectform.upload.value == None %}
                <th><input class="form-check-input" id="flexCheckDisabled" type="checkbox" onClick="toggle(this)"
                           disabled>
                </th>
                {% else %}
                <th><input class="form-check-input" id="checkAll" type="checkbox" onClick="toggle(this)"></th>
                {% endif %}
                <th class="js-sort-string">NAZWA</th>
                <th class="js-sort-number">EAN</th>
                <th class="js-sort-number">ILOŚĆ</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
            <tr class="tableElement">
                <td>
                    <input class="form-check-input" type="checkbox" name="delete" value="{{product.id}}">
                </td>
                <td>{{ product.name }}</td>
                <td>{{ product.EAN }}</td>
                <td>{{ product.quantity }}</td>
                <td><a class="nav-button" href="/inw/update/{{product.id}}"><img class="icon"
                                                                                 src="{% static 'images/edit.png' %}"></a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </form>
</div>
{% endblock %}

work_site/inw/templates/inw/upload_form_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Upload {% endblock %}

{% load static %}
{% block script %}
    <!-- Dropzone JS/CSS -->
    <script src="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone-min.js"></script>
    <link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block nav %}
<h1><img class="header-icon" src="{% static 'images/upload_icon.png' %}">Upload</h1>
{% include 'inw/messages.html' %}
{% endblock %}

{% block content %}
<form method="post" action="{% url 'myapp:upload' %}" class="dropzone" id="my-awesome-dropzone">
    {% csrf_token %}
    <div class="fallback">
        <input type="file" value="file" multiple/>
    </div>
    <button type="submit" id="button" class="invisible">Submit</button>
    <script src="{% static 'js/dropzone_settings.js' %}"></script>
</form>
<p class="info">Umieść Pliki na górze!</p>
<label for="button" class="btn btn-primary col-12" tabindex="0">Wyślij</label>


{% endblock %}