work_site/accounts/urls.py
from django.urls import path, include, reverse_lazy
from .views import CustomLoginView, ProfileView, DeleteModel, UpdateEmail, PasswordChange, UploadModelList, CreateUser, \
    password_reset_request, PasswordResetConfirm
from django.contrib.auth import views as auth_views

app_name = 'myauth'

urlpatterns = [

    path('create_user/', CreateUser.as_view(), name='create_user'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('delete_inw/<int:pk>', DeleteModel.as_view(), name='delete_inw'),
    path('update_email/<int:pk>', UpdateEmail.as_view(), name='update_email'),
    path('list/<int:pk>', UploadModelList.as_view(), name='list'),
    path('login/', CustomLoginView.as_view(template_name='accounts/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('myauth:login')), name='logout'),
    path('password_change/<int:pk>', PasswordChange.as_view(), name='password_change'),
    path('password_reset/', password_reset_request,
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/registration/password_reset_complete.html'), name='password_reset_complete'),
    # path("password_reset", views.password_reset_request, name="password_reset")

]

work_site/inw/urls.py
from django.urls import path
from .views import TableData, UploadData, InwModelCreateView, InwModelUpdateView, ConfirmDeleteList, \
    download_data_as_excel

app_name = 'myapp'

urlpatterns = [
    path('table/', TableData.as_view(), name='table'),
    path('upload/', UploadData.as_view(), name='upload'),
    path('create/', InwModelCreateView.as_view(), name='create'),
    path('update/<int:pk>', InwModelUpdateView.as_view(), name='update'),
    path('delete/', ConfirmDeleteList.as_view(), name='list'),
    path('download/', download_data_as_excel, name='download'),
    path('download/<int:pk>', download_data_as_excel, name='download'),

]

handler404 = "work_site.views.page_not_found_view"

work_site/work_site/urls.py
from django.contrib import admin
from django.urls import path,include,reverse_lazy
from .views import HomeView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inw/', include('inw.urls')),
    path('accounts/', include('accounts.urls')),
    path('', HomeView.as_view(), name='home'),
]

work_site/templates/base.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Title {% endblock %}</title>
    <!-- Faq + icon -->
        <link rel="stylesheet" href=
            "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
              integrity=
                      "sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
              crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static '/css/base.css' %}" type="text/css">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora&family=Nunito:ital,wght@1,300&family=Vollkorn&display=swap"
          rel="stylesheet">
    {% block script %}

    {% endblock %}
</head>
<body>

<nav class="nav sticky">
    <div class="navicon">
        <div></div>
    </div>
    {% if user.is_authenticated %}
    {% if user.is_superuser %}
    <a class="nav-item" href="/admin">Admin Site</a>
    {% endif %}
    <span class="nav-item-span">Zalogowany jako</span>
    <a class="nav-item" href="{% url 'myauth:profile' %}">{{user.username}}</a>
    <a class="nav-item" href="{% url 'home' %}">Home</a>
    <a class="nav-item" href="{% url 'myapp:upload' %}">Upload</a>
    <a class="nav-item" href="{% url 'myapp:table' %}">Tabela</a>
    <a class="nav-item" href="{% url 'myapp:create' %}">Dodaj</a>
    <a class="nav-item" href="{% url 'myauth:logout' %}">Wyloguj</a>
    {% else %}
    <a class="nav-item" href="{% url 'home' %}">Home</a>
    <a class="nav-item" href="{% url 'myauth:login' %}">Login</a>
    <a class="nav-item" href="{% url 'myauth:create_user' %}">Rejestracja</a>
    {% endif %}
</nav>

<div class="container">
    {% block nav %}
    {% endblock %}
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

work_site/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} FAQ {% endblock %}

{% block content %}

<h1><img class="header-icon" src="{% static 'images/home_icon.png' %}">FAQ</h1>

{% include 'inw/messages.html' %}
<div class="container-faq">
    <h2 class="faq-heading">Jak Korzystać?</h2>
    <ul>
        <li class="faq">
            <div class="question">
                Przypomnienie oraz zmiana hasła
                <span class="icon-main">
                    <i class="fa-solid fa-plus"></i>
                </span>
            </div>
            <div class="answer non-active">
                Jeśli nie pamiętasz hasła, po wybraniu opcji "zapomniałeś hasła" możesz wpisać adres mailowy który jest podany na koncie logowania,
                domyślnie powinnien być to email salonowy. Po wysłaniu maila, w ciągu kilku minut powinnien przyjść mail z jednorazowym linkiem do zmiany hasła.
            </div>
        </li>
        <li class="faq">
            <div class="question">
                Inwentaryzacja kart SIM
                <span class="icon-main">                <span class="icon-main">

                    <i class="fa-solid fa-plus"></i>
                </span>
            </div>
            <p class="answer non-active">
                Pobierz raport numerów seryjnych kart sim oraz zeskanuj do osobnego pliku excel wszystkie numery seryjne
                kart sim, numery seryjne powinny znajować się zaczynając od 1 wiersza oraz umieszczone tylko i wyłącznie
                w 1 kolumnie. Plik z zeskanowymi numerami seryjnymi powinnien mieć krótszą nazwę niż raport numerów seryjnych domyślna zalecana nazwa to "inw"
                Podczas skanowania plików możesz zauważyć iż numery seryjne nie mają początku 89480, jeśli tak się zdarzy nie dopisuj do żadnego pliku
                innych numerów, program sam je dopisze jeśli będzie taka potrzeba,
                Następnie gdy obydwa pliki są już gotowe w zakładce Upload przeciągnij bądź wybierz wyżej wspomniane dwa pliki i poczekaj na rezultat,
                Program może przetwarzać proces nawet kilka minut.
            </p>
        </li>
        <li class="faq">
            <div class="question">
                Inwentaryzacja Starterów i Akcesorii
                <span class="icon-main">
                    <i class="fa-solid fa-plus"></i>
                </span>
            </div>
            <p class="answer non-active">
                Pobierz raport numerów seryjnych akcesorii bądź starterów oraz zeskanuj do osobnego pliku excel wszystkie numery seryjne
                produktów które chcesz sprawdzić, numery seryjne powinny znajować się zaczynając od 1 wiersza oraz umieszczone tylko i wyłącznie
                w 1 kolumnie. Plik z zeskanowymi numerami seryjnymi powinnien mieć krótszą nazwę niż raport numerów seryjnych domyślna zalecana nazwa to "inw"
                Następnie gdy obydwa pliki są już gotowe w zakładce Upload przeciągnij bądź wybierz wyżej wspomniane dwa pliki i poczekaj na rezultat,
                Program może przetwarzać proces nawet kilka minut.
            </p>
        </li>
        <li class="faq">
            <div class="question">
                Kod błędu 1
                <span class="icon-main">
                    <i class="fa-solid fa-plus"></i>
                </span>
            </div>
            <div class="answer non-active">
                <p>1.Plik SAP powinnien być wgrywany bez dokonywania ręcznych modyfikacji,</p>
                <p>2.Plik SAP powinnien mieć dłuższą nazwę niż plik z inwentaryzacji,</p>
                <p>3.Sprawdź czy plik SAP zawiera wszystkie kolumny jeśli nie, pobierz go ponownie,</p>
            </div>
        </li>
        <li class="faq">
            <div class="question">
                Kod błędu 2
                <span class="icon-main">
                    <i class="fa-solid fa-plus"></i>
                </span>
            </div>
            <div class="answer non-active">
                <p>1.Sprawdź czy na pewno wgrywasz odpowiednie pliki jeden plik to raport SAP drugi plik to inwentaryzacja excel.</p>
            <p>2.Sprawdź czy w plikach nie występuje numery seryjne zawierające litery, jeśli tak usuń je.</p>
                <p>3.Sprawdź czy w pliku INW występują puste przestrzenie pomiędzy numerami seryjnymi, jeśli tak uzupełnij bądź zlikwiduj je.</p>
            </div>
        </li>
        <li class="faq">
            <div class="question">
                Nieprawidłowy wynik inwentaryzacji
                <span class="icon-main">
                    <i class="fa-solid fa-plus"></i>
                </span>
            </div>
            <p class="answer non-active">
                Sprawdź czy wszystkie numery seryjne są zeskanowe w 1 kolumnie pliku excel do którego zostały zeskanowane produkty,
                Program sprawdza jedynie numery seryjne które są widoczne w 1 kolumnie pliku excel, plik excel nie powinnien zawierać
                żadnych innych produktów w pozostałych kolumnach.
                Jeśli numery seryjne nie zgadzają się w inwetaryzacji kart sim, pamiętaj by w pliku z zeskananymi kartami nie dopisywać pierwszych
                cyfr 89480, pliki powinny zostać zeskanowane i pozostać w orginalnych numerach bez modyfikacji, jeśli będzie taka potrzeba program
                sam dopiszę brakujące numery.
            </p>
        </li>
        <li class="faq">
            <div class="question">
                What should be included in a FAQ section?
                <span class="icon-main">
                    <i class="fa-solid fa-plus"></i>
                </span>
            </div>
            <p class="answer non-active">
                Fully answer the question, don't
                just link to a different page.
            </p>
        </li>
    </ul>
</div>
<script src="{% static 'js/faq.js' %}"></script>
{% endblock %}